### ISSUE TITLE
500 server response and app error, when updating a subscription with an invalid card number

### ISSUE THREAD

**Issue by AlanDonohoe** [andrewculver/koudoku#100]
When I create a subscription with a valid card number (eg: 4242424242424242 - from stripe's test card numbers (https://stripe.com/docs/testing#cards)) and then go back and update the card details with an invalid card number (again, from stripe's test card number list eg: 4000000000000002)... I get a 500 response and then an app error... 

Here's the server logs:

method=POST path="/koudoku/owner/363/subscriptions/12" host=XXXXXX.herokuapp.com request_id=XXXXXXXX fwd="XXXXXX" dyno=web.1 connect=1ms service=2406ms status=500 bytes=1799

**Comment by yas4891** [comment]
Hi @AlanDonohoe 

can you please provide a stack trace? 
How do you include koudoku in your Gemfile? Please copy&paste the line

**Comment by yas4891** [comment]
no further details provided, closed
