### ISSUE TITLE
Required: has_one :subscription?

### ISSUE THREAD

**Issue by foureyesup** [andrewculver/koudoku#109]
Hi - I spent ages battling an "undefined method `subscription' for #<User:xxxxxxxxxxxx" error with the subscriptions#index action after installing this gem, turns out you need to add has_one :subscription to User.rb (or presumably whichever model you're using) to get it to work. Is this intentional?

Happy to submit a pull request to update the readme if so, I think it will save a lot of people time.

**Comment by yas4891** [comment]
Thanks for reporting this. 
It should be fixed in 2c9ec6dd8ab7108005b2942b58d77305b8d83627 // 1.1.2
