### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by nikolay12** [andrewculver/koudoku#119]
I tried to follow the readme but stumbled. First including the koudoku gem in the Gemfile caused a bundle error:

```
bundle install
Your Gemfile lists the gem koudoku (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that koudoku (>= 0) should come from source at . and 
. Bundler cannot continue.

 #  from /Users/nnikolo/Documents/private/rails_projects/koudoku/Gemfile:15
 #  -------------------------------------------
 #  # gem 'debugger'
 >  gem 'koudoku'
 #  -------------------------------------------
```

I removed the gem and then bundle went fine. However the next step caused another problem:

```
rails g koudoku:install user
Could not find generator 'koudoku:install'. Maybe you meant 'test_unit:mailer' or 'controller' or 'test_unit:job'
Run `rails generate --help` for more options.
```

I am stuck. Can you advise?

**Comment by yas4891** [comment]
Can you please copy and paste your entire Gemfile that is not working?

**Comment by nikolay12** [comment]
@yas4891 I just cloned the git repo:
```
source "http://rubygems.org"

# Declare your gem's dependencies in koudoku.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
```
I tried adding 

```
gem 'koudoku'
```

to the Gemfile as described in the readme but it did produce the error I mentioned. Removing the gem removed the bundle error but than I stumbled upon the second error - as I mentioned above.

**Comment by yas4891** [comment]
@nikolay12 
Hi Nikolay. 
This isn't how you use koudoku (or any other Rails engine). You need to create a full Rails app (here's a tutorial: http://guides.rubyonrails.org/getting_started.html) and then you can integrate koudoku into it. 

Additional information: http://code.tutsplus.com/articles/ruby-for-newbies-working-with-gems--net-18977

Cheers,
Christoph

**Comment by nikolay12** [comment]
@yas4891 Hi Christoph, thanks for your quick replies. You mean - I can start with an empty scaffold and than just add the gem? 

By the way, I wrote some simple rails applications from scratch and deployed them on a production server I maintain myself - so assume at least some basic rails experience on my part. I also had no trouble running Daniel Kehoe's Saas Stripe application so I think that something in Koudokou's readme (or source) is not quite right.

**Comment by yas4891** [comment]
@nikolay12 
Yes, koudoku is a Rails engine and the idea of engines is for them to be integrated into your applications. It is not intended to be (nor can it be) run as a stand-alone application. I am not familiar with Daniel's work, but from the sound of it his app was designed as a full Rails app - not an engine. 

Koudoku is a Rails engine and you integrate it into your application by following the instructions in the readme. You might be right that it could be clearer about the fact that you add koudoku to your application's Gemfile, but frankly I have never had anyone try to add it to koudoku's Gemfile. 
Just for your information, the way we phrased is ubiquitous in the Rails community as can be seen from these examples:  

https://github.com/plataformatec/devise#getting-started <https://github.com/plataformatec/devise#getting-started>
https://github.com/CanCanCommunity/cancancan#installation <https://github.com/CanCanCommunity/cancancan#installation>

Whenever someone writes "your Gemfile" they mean "your fully-fledged stand-alone Rails application's Gemfile, that you want to pimp with the functionality we provide in this gem"

Cheers,
Christoph
