### ISSUE TITLE
Pseudo conflicts reported during model generation

### ISSUE THREAD

**Issue by nikolay12** [andrewculver/koudoku#120]
My starting point is [Daniel Kehoe's Devise example](https://github.com/RailsApps/rails-devise). There is only one model there (user). 

When I run
```
rails g koudoku:install user
``` 
I am getting
```
$ rails g koudoku:install user
      create  config/initializers/koudoku.rb
    generate  model
      invoke  active_record
      create    db/migrate/20150616114740_create_subscriptions.rb
      create    app/models/subscription.rb
      invoke    rspec
      create      spec/models/subscription_spec.rb
      invoke      factory_girl
      create        spec/factories/subscriptions.rb
    conflict  app/models/subscription.rb
Overwrite /Users/nnikolo/Documents/private/rails_projects/rails-devise/app/models/subscription.rb? (enter "h" for help) [Ynaqdh]
```
There was no such model there so koudoku seems to create the model and than report it as a conflict. Same goes for the other two models created by kouroku (plan and coupon) - they are reported as conflicts althoug no such models existed.

So far it is not a show stopper - so, please, feel free to ignore this bug. I am reporting it just in case it may be a symptom of something more serious.

**Comment by yas4891** [comment]
tested and doesn't happen on a fresh install for me
