### ISSUE TITLE
No Method Error - undefined method `encoding' for nil:NilClass

### ISSUE THREAD

**Issue by juanpastas** [andrewculver/koudoku#122]
![screenshot from 2015-06-24 17 01 07](https://cloud.githubusercontent.com/assets/671721/8342638/3879ca30-1a93-11e5-8d1a-aa00b66499c4.png)

[trace](https://gist.github.com/juanpastas/4409ce3df4fa1e0dc079)

[Here](https://github.com/andrewculver/koudoku/blob/7e4e7430a9de56bb5a72eaf09cd7c55e545b88d3/app/concerns/koudoku/subscription.rb#L99) is the line.

Here are my plans:

![screenshot from 2015-06-24 17 08 20](https://cloud.githubusercontent.com/assets/671721/8342697/af8196da-1a93-11e5-8128-4f89b72ba83b.png)

And my [code](https://github.com/juanpastas/koudoku_test)

**Comment by juanpastas** [comment]
I found that `customer.default_card` is nil. Card not being created on Stripe. Customer and Subscription do.

**Comment by juanpastas** [comment]
I found my problem. I was not setting ENV variable. I solved it installing figaro.

Now I have another problem:

![screenshot from 2015-06-24 19 28 14](https://cloud.githubusercontent.com/assets/671721/8344427/36161af0-1aa7-11e5-9e13-4e65ba5c73e4.png)


`customer.cards` is raises error. Any advice?

**Comment by juanpastas** [comment]
I found [it](https://stripe.com/docs/api#retrieve_card) `cards` is now `sources`

**Comment by yas4891** [comment]
@juanpastas 
Hi,

can you please check your `config/initializers/koudoku.rb` and make sure that this line is present: 

`Stripe.api_version = '2015-01-11'`

The bug you're reporting was fixed in version 1.1.1 - so it seems strange to me that you should still see it.

**Comment by juanpastas** [comment]
I'll try. Thanks.
