### ISSUE TITLE
User is charged but the app throws an error

### ISSUE THREAD

**Issue by FanaHOVA** [andrewculver/koudoku#128]
Yesterday I had everything working successfully with the gem, payments went through and everything worked fine. I had to rollback my Rails installation to fix an issue with Devise and finally got everything to work again but when I try to subscribe I get the 
    
    undefined method `cards' for #<Stripe::Customer:0x00000005f54fb0>

error. The problem is that my user account doesn't get the subscription but they are charged since I see the payments in my Stripe dashboard. Anybody had this issue before? [Here's the full trace](http://pastebin.com/QzjjMxiA)

**Comment by FanaHOVA** [comment]
@yas4891 here it is!

**Comment by yas4891** [comment]
can you please check your `config/initializers/koudoku.rb` for the line `Stripe.api_version = '2015-01-11'` ?

Please make sure that it is there.

**Comment by FanaHOVA** [comment]
@yas4891 Tried that, I've also tried with the latest version of the API (2015-07-07) but I get the same error!

**Comment by yas4891** [comment]
strange, because enforcing the old API version has proven time and again to solve that specific error. 
What version of Koudoku are you using?

**Comment by FanaHOVA** [comment]
@yas4891 My bad. After reading previous issues I tried to install @confact's build with his fix but it didn't work and I forgot to remove the :git to his repo in the gemfile since I went for lunch. I shouldn't work on the weekend. Thanks man!

**Comment by yas4891** [comment]
@FanaHOVA You're welcome. That'll be $695.00 ;-)

**Comment by FanaHOVA** [comment]
@yas4891 Haha dang! I'll repay with new views for the gem since the default ones are pretty blank!
