### ISSUE TITLE
Change Currency?

### ISSUE THREAD

**Issue by stemitchell91** [andrewculver/koudoku#130]
Is it possible to use a currency other than US dollars? I've looked all through the code for this gem and I can't find where the currency is set.

**Comment by yas4891** [comment]
You can set the currency at the time you create a plan through the [Stripe dashboard](dashboard.stripe.com/dashboard). 
Then you just connect the `Stripe::Plan` to the `Koudoku::Plan` by setting `Koudoku::Plan#stripe_id = Stripe::Plan#id`. 
I hope this clarifies things for you

**Comment by stemitchell91** [comment]
Ah, I see. Thanks very much, it hadn't occurred to me that it would work like that.
