### ISSUE TITLE
Changes made via Stripe Dashboard not reflected in app

### ISSUE THREAD

**Issue by razvanh** [andrewculver/koudoku#133]
If I cancel a subscription using the Stripe dashboard, the change is not reflected in my app. When I get the subscription info in my app, I still see the customer as subscribed.

**Comment by yas4891** [comment]
did you implement webhooks?

**Comment by razvanh** [comment]
No, I haven't. I am not sure how that would even work since my Dashboard api version is newer than the one specified in the koudoku config file.

So I would need webhooks to work in order to achieve this?

**Comment by yas4891** [comment]
it should work across API versions and you need webhooks for this to work.
