### ISSUE TITLE
Undefined method 'layout=' after running install

### ISSUE THREAD

**Issue by bholdman** [andrewculver/koudoku#135]
After running rails g koudoku:install user I receive the following error:

/koudoku.rb:11:in `block in <top (required)>': undefined method `layout=' for Koudoku:Module (NoMethodError)

with a long list of other errors below it.

**Comment by raitom** [comment]
I got this error too with Rails 4.2.

**Comment by yas4891** [comment]
which version of Koudoku are you using?

**Comment by raitom** [comment]
1.2.3

**Comment by yas4891** [comment]
can you try the recently released 1.2.4?

**Comment by raitom** [comment]
Problem fixed with the 1.2.4 version.

**Comment by azurewraith** [comment]
I ran into this issue yesterday also, and 1.2.4 fixes it!

**Comment by yas4891** [comment]
Perfect! Thanks for reporting and if you have any more problems with Koudoku, let me know @raitom @bholdman
