### ISSUE TITLE
Charge upon subscription (upfront payments)

### ISSUE THREAD

**Issue by dyatlov** [andrewculver/koudoku#138]
Sorry if it was written somewhere but I didn't find that.
When I assign subscription to a user, will the user be charged immediately?
We need our users to pay in advance/upfront, so when someone subscribes to our plan we have to charge them now, not in a month..
It seems to me that the only way to achieve this is to charge them first time through Stripe API directy..?

**Comment by yas4891** [comment]
we create a standard Stripe::Subscription based on a Stripe::Plan. Those are charged upfront.
