### ISSUE TITLE
Getting error in Javascript : "Uncaught Error: You are using a secret key with Stripe.js, instead of the publishable one."

### ISSUE THREAD

**Issue by nishant-shrivastava** [andrewculver/koudoku#146]
I have been trying to integrate gem to one of our App where we will have subscriptions. The problem is, I have been getting this error -

"Uncaught Error: You are using a secret key with Stripe.js, instead of the publishable one."
Though I have put it like it's there in the example;

```
Stripe.setPublishableKey("#{Koudoku.stripe_publishable_key}");
```

I have followed the same process given in the example, and above is the error which I get through javascript. And below is the error which I get after form-post;

```
"The provided key 'pk_test_************************' does not have the required permissions for this endpoint on account 'acct_****************'. Having more permission would allow this request to continue."
```

Can you please guide me in this error, please.

**Comment by yas4891** [comment]
The error message indicates that you are using the wrong (secret) key for the publishable key. 
What are your environment variables set to? 

I have not experienced the second error, but the error message seems pretty clear to me. Have you added the required permissions for that key?

**Comment by nishant-shrivastava** [comment]
Thanks Guys for the quick reply. Some how I mixed up the keys in my App's configuration, as I am using another gem to handle it (configurations). Moving ahead!

Thanks Again.

**Comment by rahul-nath** [comment]
For anyone who cares: The publishable key should be used on your front end (when you load stripe), and your secret key should be used on any backend API requests (if any) you make.

**Comment by MyElectricSheep** [comment]
Thanks @rahul-nath ! Always cool to share, worked for me 😁 !
