### ISSUE TITLE
Multi-Model Support for Koudoku

### ISSUE THREAD

**Issue by RailsCod3rFuture** [andrewculver/koudoku#196]
I have a User model and an Employer model with different stripe subscriptions. What approach should I take to support each model without causing issues?

**Comment by RailsCod3rFuture** [comment]
In the case below, **config.subscriptions_owned_by = :user**. How can I include the employer on this line, alongside the user?

```
# /config/initializers/koudoku.rb
Koudoku.setup do |config|
  config.subscriptions_owned_by = :user
  config.stripe_publishable_key = ENV['STRIPE_PUBLISHABLE_KEY']
  config.stripe_secret_key = ENV['STRIPE_SECRET_KEY']
  
  # add webhooks
  config.subscribe 'charge.failed', YourChargeFailed
end

```

**Comment by andrewculver** [comment]
Koudoku doesn't currently support this use case, so you'd have to implement it yourself. It will certainly be a lot of effort, but if you do get this working, please consider submitting a pull request so others can benefit as well!
