### ISSUE TITLE
Upgrades vs. downgrades should be based on prices, not plan IDs.

### ISSUE THREAD

**Issue by andrewculver** [andrewculver/koudoku#6]

**Comment by desmondhume** [comment]
Where is it closed? I still see the id based comparison
https://github.com/andrewculver/koudoku/blob/9e73e64e5520d2f6a5c144f336d2792f5e404670/app/concerns/koudoku/subscription.rb#L192-L198

Am I missing something?

**Comment by snowmoonsoftware** [comment]
Related to #99
