### ISSUE TITLE
Response body error:  Stripe::InvalidRequestError

### ISSUE THREAD

**Issue by lgs** [andrewculver/koudoku#72]
I get Response body error: Stripe::InvalidRequestError

<pre>
Stripe::InvalidRequestError at /users/1/subscriptions
This customer has no attached card
</pre>

env:

<pre>
lsoave@basenode:~/test/koudoku-omniauth$ grep koudoku Gemfile.lock 
  remote: https://github.com/andrewculver/koudoku.git
    koudoku (0.0.11)
  koudoku!
</pre>

stacktrace:

<pre>
lsoave@basenode:~/test/koudoku-omniauth$ rails s 
=> Booting WEBrick
=> Rails 4.1.6 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
[2014-09-28 18:02:57] INFO  WEBrick 1.3.1
[2014-09-28 18:02:57] INFO  ruby 2.1.2 (2014-05-08) [x86_64-linux]
[2014-09-28 18:02:57] INFO  WEBrick::HTTPServer#start: pid=26155 port=3000

Started GET "/" for 127.0.0.1 at 2014-09-28 18:06:06 +0200
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by Rails::WelcomeController#index as HTML
  Rendered /home/lsoave/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/templates/rails/welcome/index.html.erb (1.2ms)
Completed 200 OK in 12ms (Views: 5.2ms | ActiveRecord: 0.0ms)

Started GET "/pricing" for 127.0.0.1 at 2014-09-28 18:06:10 +0200
Processing by Koudoku::SubscriptionsController#index as HTML
  User Load (0.2ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
  Subscription Load (0.1ms)  SELECT  "subscriptions".* FROM "subscriptions"  WHERE "subscriptions"."user_id" = ? LIMIT 1  [["user_id", 1]]
  Plan Load (0.2ms)  SELECT "plans".* FROM "plans"   ORDER BY "plans"."display_order" ASC
  Rendered koudoku/subscriptions/_social_proof.html.erb (0.3ms)
  Rendered koudoku/subscriptions/_pricing_table.html.erb (17.9ms)
  Rendered koudoku/subscriptions/index.html.erb within layouts/application (19.9ms)
Completed 200 OK in 119ms (Views: 92.9ms | ActiveRecord: 1.2ms)

Started GET "/koudoku/subscriptions/new?plan=1" for 127.0.0.1 at 2014-09-28 18:06:12 +0200
Processing by Koudoku::SubscriptionsController#new as HTML
  Parameters: {"plan"=>"1"}
  User Load (0.1ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
Redirected to http://localhost:3000/koudoku/users/1/subscriptions/new?plan=1
Completed 302 Found in 2ms (ActiveRecord: 0.1ms)

Started GET "/koudoku/users/1/subscriptions/new?plan=1" for 127.0.0.1 at 2014-09-28 18:06:12 +0200
Processing by Koudoku::SubscriptionsController#new as HTML
  Parameters: {"plan"=>"1", "owner_id"=>"1"}
  User Load (0.1ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
  User Load (0.1ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
  Subscription Load (0.1ms)  SELECT  "subscriptions".* FROM "subscriptions"  WHERE "subscriptions"."user_id" = ? LIMIT 1  [["user_id", 1]]
  Plan Load (0.1ms)  SELECT  "plans".* FROM "plans"  WHERE "plans"."id" = ? LIMIT 1  [["id", 1]]
  Rendered koudoku/subscriptions/_card.html.erb (12.4ms)
  Rendered koudoku/subscriptions/new.html.erb within layouts/application (13.5ms)
Completed 200 OK in 63ms (Views: 57.2ms | ActiveRecord: 0.7ms)

Started POST "/koudoku/users/1/subscriptions" for 127.0.0.1 at 2014-09-28 18:06:41 +0200
Processing by Koudoku::SubscriptionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"HQiU89eI8ptbmex4joeAvXMVNKRBPOPFnxq2lEey0Jg=", "subscription"=>{"plan_id"=>"1"}, "owner_id"=>"1"}
  User Load (0.2ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
  User Load (0.1ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = ? LIMIT 1  [["id", 1]]
  Subscription Load (0.1ms)  SELECT  "subscriptions".* FROM "subscriptions"  WHERE "subscriptions"."user_id" = ? LIMIT 1  [["user_id", 1]]
   (0.2ms)  begin transaction
  Plan Load (0.1ms)  SELECT  "plans".* FROM "plans"  WHERE "plans"."id" = ? LIMIT 1  [["id", 1]]
   (0.2ms)  rollback transaction
Completed 500 Internal Server Error in 2310ms

Stripe::InvalidRequestError - This customer has no attached card:
  stripe (1.15.0) lib/stripe.rb:232:in `handle_api_error'
  stripe (1.15.0) lib/stripe.rb:126:in `rescue in request'
  stripe (1.15.0) lib/stripe.rb:112:in `request'
  stripe (1.15.0) lib/stripe/customer.rb:39:in `update_subscription'
   () home/lsoave/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/koudoku-4f3fb7250539/app/concerns/koudoku/subscription.rb:87:in `processing!'
  activesupport (4.1.6) lib/active_support/callbacks.rb:424:in `block in make_lambda'
  activesupport (4.1.6) lib/active_support/callbacks.rb:160:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:160:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `run_callbacks'
  activerecord (4.1.6) lib/active_record/callbacks.rb:302:in `create_or_update'
  activerecord (4.1.6) lib/active_record/persistence.rb:103:in `save'
  activerecord (4.1.6) lib/active_record/validations.rb:51:in `save'
  activerecord (4.1.6) lib/active_record/attribute_methods/dirty.rb:21:in `save'
  activerecord (4.1.6) lib/active_record/transactions.rb:268:in `block (2 levels) in save'
  activerecord (4.1.6) lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
  activerecord (4.1.6) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (4.1.6) lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
  activerecord (4.1.6) lib/active_record/transactions.rb:268:in `block in save'
  activerecord (4.1.6) lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
  activerecord (4.1.6) lib/active_record/transactions.rb:267:in `save'
   () home/lsoave/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/koudoku-4f3fb7250539/app/controllers/koudoku/subscriptions_controller.rb:119:in `create'
  actionpack (4.1.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.6) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.6) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.6) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.6) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.6) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.6) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'
  railties (4.1.6) lib/rails/engine.rb:514:in `call'
  railties (4.1.6) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.6) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'
   () home/lsoave/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/omniauth-18f8fb8e7ecf/lib/omniauth/strategy.rb:186:in `call!'
   () home/lsoave/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/omniauth-18f8fb8e7ecf/lib/omniauth/strategy.rb:164:in `call'
   () home/lsoave/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/omniauth-18f8fb8e7ecf/lib/omniauth/builder.rb:59:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.6) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.6) lib/rails/engine.rb:514:in `call'
  railties (4.1.6) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /home/lsoave/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /home/lsoave/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /home/lsoave/.rbenv/versions/2.1.2/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

Started POST "/koudoku/__better_errors/bd61193907fc4acc/variables" for 127.0.0.1 at 2014-09-28 18:06:44 +0200
</pre>

**Comment by CaptainChemist** [comment]
Is there a good way to disable turbolinks only for that particular page? I am trying iterations of this at the beginning of my body to no avail:
<% content_for :body do %>
<% if controller.controller_name == 'subscriptions' || controller.controller_name == 'users' %>
        <body data-no-turbolink="true">
% end %>

**Comment by richill** [comment]
turning off the tubolink also solved my problem. in my application.js file i removed //= require turbolinks all working now and i no longer receive the error `Stripe::InvalidRequestError (This customer has no attached payment source):`
