### ISSUE TITLE
Circular dependency for Coupon upon submit

### ISSUE THREAD

**Issue by CaptainChemist** [andrewculver/koudoku#91]
I installed Koudoku just fine and added a plan to my database but when I go to try out the credit card authorization, I enter the card number and other information but when I press submit, I am greeted with this error:
Unable to autoload constant Coupon, expected /Users/me/development/rutile/app/models/coupon.rb to define it
I have not created any coupons yet, is that required? I'd prefer not to start with coupons to start but I do like the option of adding them later. Also, I added the plan manually in rails console, is there a better way to do that through one of the views? (I have a separate admin and users controller if that clarifies things.)
Thanks for the great gem!

**Comment by CaptainChemist** [comment]
I think I have it. The coupon model is incorrect in the most recent version, it should read:
class Coupon < ActiveRecord::Base
  
  has_many :subscriptions

end

**Comment by yas4891** [comment]
Hi,

Thanks for the catch! I just updated the generator. 

Cheers,
Christoph
