### ISSUE TITLE
Plan has invalid associations

### ISSUE THREAD

**Issue by snowmoonsoftware** [andrewculver/koudoku#98]
I just installed and configured koudoku -- how do you pronounce that anyway? -- and found the `Plan` model has the following:

```ruby
belongs_to :user
belongs_to :coupon
```

but the schema does not contain neither `coupon_id` nor `user_id`:

```ruby
  create_table "plans", force: :cascade do |t|
    t.string   "name",          limit: 255
    t.string   "stripe_id",     limit: 255
    t.float    "price",         limit: 24
    t.string   "interval",      limit: 255
    t.text     "features",      limit: 65535
    t.boolean  "highlight",     limit: 1
    t.integer  "display_order", limit: 4
    t.datetime "created_at",                  null: false
    t.datetime "updated_at",                  null: false
  end
````

**Comment by yas4891** [comment]
Thanks for pointing this out. 
I'll have a look at the source code. Did you use the repository at andrewculver/koudoku/master or  rubygems?

**Comment by snowmoonsoftware** [comment]
I am using master. Thanks for looking in to this.

**Comment by yas4891** [comment]
@snowmoonsoftware Fixed this in the latest master. Thanks for reporting!
